server:
  port: 8083

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8084
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 172857963583-o8643qod894lu5sh22dqig1ojk1htaep.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8083/login/oauth2/code/google"
            scope: email, profile
    jwt:
      secret: 8h10tHJZHISS8mFvpnqSUZe/QRD6ICFHMdVnPD2d4FA=
      access-token-validity: 3600
      refresh-token-validity: 86400

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.security: DEBUG
      org.springframework.security.web.FilterChainProxy: TRACE