services:
  user-postgres:
    image: postgres:15.0
    container_name: user-postgres
    ports:
      - "5433:5432"
    volumes:
      - ./infrastructure/databases/user:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-U", "postgres", "-p", "5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-postgres:
    image: postgres:15.0
    container_name: auth-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-U", "postgres", "-p", "5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  product-mongo:
    image: mongo:7.0
    container_name: product-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-postgres:
    image: postgres:15.0
    container_name: inventory-postgres
    ports:
      - "5435:5432"
    volumes:
      - ./infrastructure/databases/inventory:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-p", "5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-postgres:
    image: postgres:15.0
    container_name: order-postgres
    ports:
      - "5436:5432"
    volumes:
      - ./infrastructure/databases/order:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-p", "5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-mongo:
    image: mongo:7.0
    container_name: notification-mongo
    ports:
      - "27018:27017"
    volumes:
      - ./infrastructure/databases/notification-mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: notification_db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8084:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - redpanda
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/subjects" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,EXTERNAL://localhost:29092
    healthcheck:
      test: [ "CMD", "rpk", "cluster", "health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      user-postgres:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      auth-postgres:
        condition: service_healthy
      user-postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  product-service:
    image: product-service:latest
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      product-mongo:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://product-mongo:27017/product_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
      - "50051:50051"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      inventory-postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      PRODUCT_SERVICE_URL: http://product-service:8080

  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
      - "50052:50051"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      order-postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      INVENTORY_SERVICE_GRPC_URL: inventory-service:50051

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      notification-mongo:
        condition: service_healthy
      redpanda:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://notification-mongo:27017/notification_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081