apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile }}
          volumeMounts:
            - name: config-volume
              mountPath: /config/application-k8s.yml
              subPath: application-k8s.yml
      volumes:
        - name: config-volume
          configMap:
            name: auth-config
            items:
              - key: application-k8s.yml
                path: application-k8s.yml