spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://user-postgres:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: redpanda:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://schema-registry:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}