/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kika.avro.order;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderStatusChangedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7109109358433474253L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderStatusChangedEvent\",\"namespace\":\"com.kika.avro.order\",\"fields\":[{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"oldStatus\",\"type\":\"string\"},{\"name\":\"newStatus\",\"type\":\"string\"},{\"name\":\"occurredAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<OrderStatusChangedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderStatusChangedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderStatusChangedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderStatusChangedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderStatusChangedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderStatusChangedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderStatusChangedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderStatusChangedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderStatusChangedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long orderId;
  private long userId;
  private java.lang.CharSequence oldStatus;
  private java.lang.CharSequence newStatus;
  private java.time.Instant occurredAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderStatusChangedEvent() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param userId The new value for userId
   * @param oldStatus The new value for oldStatus
   * @param newStatus The new value for newStatus
   * @param occurredAt The new value for occurredAt
   */
  public OrderStatusChangedEvent(java.lang.Long orderId, java.lang.Long userId, java.lang.CharSequence oldStatus, java.lang.CharSequence newStatus, java.time.Instant occurredAt) {
    this.orderId = orderId;
    this.userId = userId;
    this.oldStatus = oldStatus;
    this.newStatus = newStatus;
    this.occurredAt = occurredAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return userId;
    case 2: return oldStatus;
    case 3: return newStatus;
    case 4: return occurredAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.Long)value$; break;
    case 1: userId = (java.lang.Long)value$; break;
    case 2: oldStatus = (java.lang.CharSequence)value$; break;
    case 3: newStatus = (java.lang.CharSequence)value$; break;
    case 4: occurredAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public long getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'oldStatus' field.
   * @return The value of the 'oldStatus' field.
   */
  public java.lang.CharSequence getOldStatus() {
    return oldStatus;
  }


  /**
   * Sets the value of the 'oldStatus' field.
   * @param value the value to set.
   */
  public void setOldStatus(java.lang.CharSequence value) {
    this.oldStatus = value;
  }

  /**
   * Gets the value of the 'newStatus' field.
   * @return The value of the 'newStatus' field.
   */
  public java.lang.CharSequence getNewStatus() {
    return newStatus;
  }


  /**
   * Sets the value of the 'newStatus' field.
   * @param value the value to set.
   */
  public void setNewStatus(java.lang.CharSequence value) {
    this.newStatus = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return The value of the 'occurredAt' field.
   */
  public java.time.Instant getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * @param value the value to set.
   */
  public void setOccurredAt(java.time.Instant value) {
    this.occurredAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new OrderStatusChangedEvent RecordBuilder.
   * @return A new OrderStatusChangedEvent RecordBuilder
   */
  public static com.kika.avro.order.OrderStatusChangedEvent.Builder newBuilder() {
    return new com.kika.avro.order.OrderStatusChangedEvent.Builder();
  }

  /**
   * Creates a new OrderStatusChangedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderStatusChangedEvent RecordBuilder
   */
  public static com.kika.avro.order.OrderStatusChangedEvent.Builder newBuilder(com.kika.avro.order.OrderStatusChangedEvent.Builder other) {
    if (other == null) {
      return new com.kika.avro.order.OrderStatusChangedEvent.Builder();
    } else {
      return new com.kika.avro.order.OrderStatusChangedEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderStatusChangedEvent RecordBuilder by copying an existing OrderStatusChangedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderStatusChangedEvent RecordBuilder
   */
  public static com.kika.avro.order.OrderStatusChangedEvent.Builder newBuilder(com.kika.avro.order.OrderStatusChangedEvent other) {
    if (other == null) {
      return new com.kika.avro.order.OrderStatusChangedEvent.Builder();
    } else {
      return new com.kika.avro.order.OrderStatusChangedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderStatusChangedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderStatusChangedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderStatusChangedEvent> {

    private long orderId;
    private long userId;
    private java.lang.CharSequence oldStatus;
    private java.lang.CharSequence newStatus;
    private java.time.Instant occurredAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kika.avro.order.OrderStatusChangedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.oldStatus)) {
        this.oldStatus = data().deepCopy(fields()[2].schema(), other.oldStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.newStatus)) {
        this.newStatus = data().deepCopy(fields()[3].schema(), other.newStatus);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[4].schema(), other.occurredAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderStatusChangedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kika.avro.order.OrderStatusChangedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.oldStatus)) {
        this.oldStatus = data().deepCopy(fields()[2].schema(), other.oldStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.newStatus)) {
        this.newStatus = data().deepCopy(fields()[3].schema(), other.newStatus);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[4].schema(), other.occurredAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public long getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder setOrderId(long value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder setUserId(long value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder clearUserId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'oldStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getOldStatus() {
      return oldStatus;
    }


    /**
      * Sets the value of the 'oldStatus' field.
      * @param value The value of 'oldStatus'.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder setOldStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.oldStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'oldStatus' field has been set.
      * @return True if the 'oldStatus' field has been set, false otherwise.
      */
    public boolean hasOldStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'oldStatus' field.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder clearOldStatus() {
      oldStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'newStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewStatus() {
      return newStatus;
    }


    /**
      * Sets the value of the 'newStatus' field.
      * @param value The value of 'newStatus'.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder setNewStatus(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.newStatus = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'newStatus' field has been set.
      * @return True if the 'newStatus' field has been set, false otherwise.
      */
    public boolean hasNewStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'newStatus' field.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder clearNewStatus() {
      newStatus = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * @return The value.
      */
    public java.time.Instant getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder setOccurredAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.occurredAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * @return This builder.
      */
    public com.kika.avro.order.OrderStatusChangedEvent.Builder clearOccurredAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderStatusChangedEvent build() {
      try {
        OrderStatusChangedEvent record = new OrderStatusChangedEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.Long) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.Long) defaultValue(fields()[1]);
        record.oldStatus = fieldSetFlags()[2] ? this.oldStatus : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.newStatus = fieldSetFlags()[3] ? this.newStatus : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.occurredAt = fieldSetFlags()[4] ? this.occurredAt : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderStatusChangedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderStatusChangedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderStatusChangedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderStatusChangedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










