server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      schema:
        registry:
          url: http://localhost:8084

grpc:
  server:
    port: 50051