apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "user-service.name" . }}
    chart: {{ include "user-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "user-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-user-db:5432/user_db
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}
            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: {{ .Values.env.SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}